services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: travelport-api:local
    pull_policy: never

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: travelport-web:local
    pull_policy: never
