export const endpoints = {
  auth: {
    register:       '/auth/register',
    login:          '/auth/login',
    refresh:        '/auth/refresh',
    logout:         '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword:  '/auth/reset-password',
    verifyEmail:    '/auth/verify-email',
  },
  flights: {
    search:  '/flights/search',
    byId:    (id: string) => `/flights/${id}`,
    book:    '/flights/book',
    popular: '/flights/popular',
  },
  hotels: {
    search:  '/hotels/search',
    byId:    (id: string) => `/hotels/${id}`,
    rooms:   (id: string) => `/hotels/${id}/rooms`,
    reviews: (id: string) => `/hotels/${id}/reviews`,
    book:    '/hotels/book',
  },
  buses: {
    search:       '/buses/search',
    book:         '/buses/book',
    lockSeats:    (busId: string) => `/buses/${busId}/seats/lock`,
    lockedSeats:  (busId: string) => `/buses/${busId}/seats/locked`,
  },
  trains: {
    search: '/trains/search',
    book:   '/trains/book',
  },
  cabs: {
    search: '/cabs/search',
    book:   '/cabs/book',
  },
  bookings: {
    list:    '/bookings',
    byId:    (id: string) => `/bookings/${id}`,
    cancel:  (id: string) => `/bookings/${id}/cancel`,
    invoice: (id: string) => `/bookings/${id}/invoice`,
  },
  users: {
    profile:            '/users/profile',
    wallet:             '/users/wallet',
    walletTopup:        '/users/wallet/topup',
    walletTransactions: '/users/wallet/transactions',
    travellers:         '/users/travellers',
    traveller:          (id: string) => `/users/travellers/${id}`,
    cards:              '/users/cards',
    card:               (id: string) => `/users/cards/${id}`,
    cardDefault:        (id: string) => `/users/cards/${id}/default`,
  },
  admin: {
    dashboard:              '/admin/dashboard',
    analytics:              '/admin/analytics',
    users:                  '/admin/users',
    blockUser:              (id: string) => `/admin/users/${id}/block`,
    bookings:               '/admin/bookings',
    coupons:                '/admin/coupons',
    coupon:                 (id: string) => `/admin/coupons/${id}`,
    hotels:                 '/admin/hotels',
    toggleHotel:            (id: string) => `/admin/hotels/${id}/toggle`,
    deleteHotelReview:      (id: string) => `/admin/hotels/reviews/${id}`,
    flightOperators:        '/admin/flight-operators',
    toggleFlightOperator:   (id: string) => `/admin/flight-operators/${id}/toggle`,
    busOperators:           '/admin/bus-operators',
    toggleBusOperator:      (id: string) => `/admin/bus-operators/${id}/toggle`,
    cabOperators:           '/admin/cab-operators',
    toggleCabOperator:      (id: string) => `/admin/cab-operators/${id}/toggle`,
    flights:                '/admin/flights',
    flight:                 (id: string) => `/admin/flights/${id}`,
    couponAnalytics:        '/admin/coupons/analytics',
    userOverview:           (id: string) => `/admin/users/${id}/overview`,
    exportCsv:              '/admin/bookings/export-csv',
  },
  announcements: {
    active: '/announcements/active',
    all:    '/announcements',
    item:   (id: string) => `/announcements/${id}`,
  },
  flightOperator: {
    dashboard: '/flight-operator/dashboard',
    flights:   '/flight-operator/flights',
    flight:    (id: string) => `/flight-operator/flights/${id}`,
    bookings:  '/flight-operator/bookings',
  },
  busOperator: {
    dashboard: '/bus-operator/dashboard',
    bookings:  '/bus-operator/bookings',
  },
  cabOperator: {
    dashboard: '/cab-operator/dashboard',
    bookings:  '/cab-operator/bookings',
  },
  hotelManager: {
    dashboard:       '/hotel-manager/dashboard',
    bookings:        '/hotel-manager/bookings',
    booking:         (id: string) => `/hotel-manager/bookings/${id}`,
    checkIn:         (id: string) => `/hotel-manager/bookings/${id}/checkin`,
    charges:         (id: string) => `/hotel-manager/bookings/${id}/charges`,
    charge:          (bookingId: string, chargeId: string) => `/hotel-manager/bookings/${bookingId}/charges/${chargeId}`,
    invoice:         (id: string) => `/hotel-manager/bookings/${id}/invoice`,
    checkout:        (id: string) => `/hotel-manager/bookings/${id}/checkout`,
    availability:    '/hotel-manager/availability',
    profile:         '/hotel-manager/profile',
    rooms:           '/hotel-manager/rooms',
    room:            (id: string) => `/hotel-manager/rooms/${id}`,
  },
  payments: {
    initiate: '/payments/initiate',
    verify:   '/payments/verify',
    status:   (id: string) => `/payments/${id}`,
  },
  coupons: {
    validate: '/coupons/validate',
    featured: '/coupons/featured',
  },
  ai: {
    chat:            '/ai/chat',
    nlSearch:        '/ai/nl-search',
    recommendations: '/ai/recommendations',
    tripPlan:        '/ai/trip-plan',
    priceInsight:    '/ai/price-insight',
  },
}
